---

version: '3.8'

services:
  listener:
    build:
      context: .
      args:
        DEBIAN_BASE_IMAGE_TAG: buster-slim
        DOCKERHUB_CACHE: artifacts.knut.univention.de/dockerhub_proxy_cache/library/

...
