---

version: '3.8'

services:
  listener:
    platform: linux/amd64
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-listener-base/listener-base-debug:latest
    build:
      context: .
      args:
        DEBIAN_BASE_IMAGE_TAG: buster-slim
    env_file: .env.listener
    secrets:
      - ca_cert
      - cert_pem
      - ldap_secret
    volumes:
      - listener-data:/var/lib/univention-directory-listener/:rw

secrets:
  ca_cert:
    file: ssl/certs/CAcert.pem
  cert_pem:
    file: ssl/certs/cert.pem
  ldap_secret:
    file: secret/ldap.secret
volumes:
  listener-data:

...
