---

version: '3.8'

services:
  listener:
    build:
      context: .
      args:
        DEBIAN_BASE_IMAGE_TAG: buster-slim
        DOCKERHUB_CACHE: artifacts.knut.univention.de/dockerhub_proxy_cache/library/
        LABEL_CREATED: "${CI_JOB_STARTED_AT}"
        LABEL_REVISION: "${CI_COMMIT_SHA}"
        LABEL_SOURCE: "${CI_PROJECT_URL}"
        LABEL_VERSION: "${CI_PIPELINE_ID}"

...
