---

version: '3.8'

services:
  listener:
    env_file: .env.listener
    secrets:
    - ca_cert
    - cert_pem

secrets:
  ca_cert:
    file: ssl/certs/CAcert.pem
  cert_pem:
    file: ssl/certs/cert.pem

volumes:
  listener-data:

...
