---

version: '3.8'

services:
  listener:
    platform: linux/amd64
    image: artifacts.knut.univention.de/upx/upx-listener-base:latest
    build:
      context: .
      args:
        DEBIAN_BASE_IMAGE_TAG: buster-slim
        # DOCKERHUB_CACHE: artifacts.knut.univention.de/dockerhub_proxy_cache/library/
        LABEL_CREATED: "${CI_JOB_STARTED_AT}"
        LABEL_REVISION: "${CI_COMMIT_SHA}"
        LABEL_SOURCE: "${CI_PROJECT_URL}"
        LABEL_VERSION: "${CI_PIPELINE_ID}"
    extra_hosts:
      ucs-5746.univention.intranet: "10.200.115.20"

...
