---

version: '3.8'

services:
  listener:
    env_file: .env.listener
    secrets:
      - ca_cert
      - cert_pem
      - ldap_secret
    volumes:
      - listener-data:/var/lib/univention-directory-listener/:rw

secrets:
  ca_cert:
    file: ssl/certs/CAcert.pem
  cert_pem:
    file: ssl/certs/cert.pem
  ldap_secret:
    file: secret/ldap.secret
volumes:
  listener-data:

...
