# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---

services:
  listener-base-debug:
    container_name: "listener-base-debug"
    platform: "linux/amd64"
    image: "gitregistry.knut.univention.de/univention/customers/dataport/upx/container-listener-base/listener-base:latest"
    build:
      context: "."
    environment:
      # The default configuration matches the state in "container-ldap".
      # See "docker-compose.override.yaml.example" how to tweak this to your needs.
      LDAP_HOST: "listener-base-ldap-server"
      LDAP_BASE_DN: "dc=univention-organization,dc=intranet"
      # TODO: Set to a reasonable default value, "container-ldap" does not have this yet.
      LDAP_HOST_DN: "cn=ucs-5746,cn=dc,cn=computers,dc=univention-organization,dc=intranet"
      NOTIFIER_SERVER: "listener-base-ldap-notifier"

      DEBUG_LEVEL: "5"
      # Whether to start encryption and validate certificates.
      # Chose from "off", "unvalidated" and "secure".
      TLS_MODE: "off"
      LDAP_PASSWORD: "ldap-password"
      LDAP_PASSWORD_FILE: "/var/secrets/ldap_secret"
    volumes:
      - "listener-data:/var/lib/univention-directory-listener/:rw"
    depends_on:
      ldap-notifier:
        condition: "service_healthy"
      ldap-server:
        condition: "service_healthy"

  ldap-notifier:
    container_name: "listener-base-ldap-notifier"
    platform: "linux/amd64"
    image: "gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/ldap-notifier:latest"
    ports:
      - "6669:6669"
    volumes:
      - "ldap-shared-data:/var/lib/univention-ldap/:rw"
      - "ldap-shared-run:/var/run/slapd/:ro"
    depends_on:
      ldap-server:
        condition: "service_healthy"
    healthcheck:
      test: "bash -c 'echo > /dev/tcp/localhost/6669'"
      interval: "2s"
      timeout: "1s"
      retries: 10
      start_period: "5s"

  ldap-server:
    container_name: "listener-base-ldap-server"
    platform: "linux/amd64"
    image: "gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/ldap-server:latest"
    environment:
      DOMAIN_NAME: "univention-organization.intranet"
      LDAP_BASE_DN: "dc=univention-organization,dc=intranet"
      # For binding with user "cn=admin,${LDAP_BASE_DN}"
      LDAP_CN_ADMIN_PW: "ldap-password"
    ports:
      - "389:389"
    volumes:
      - "ldap-shared-data:/var/lib/univention-ldap/:rw"
      - "ldap-shared-run:/var/run/slapd/:rw"
    healthcheck:
      test: "bash -c 'echo > /dev/tcp/localhost/389'"
      interval: "2s"
      timeout: "1s"
      retries: 10
      start_period: "5s"

  ldap-admin:
    container_name: "listener-base-ldap-admin"
    image: "osixia/phpldapadmin:0.9.0"
    platform: "linux/amd64"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'listener-base-ldap-server':{'login':{'bind_id':'cn=admin,dc=univention-organization,dc=intranet'}}}]"
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_LDAP_CLIENT_TLS: "true"
      PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: "never"
    ports:
      - "8080:80"
    depends_on:
      ldap-server:
        condition: "service_healthy"
    healthcheck:
      test: "bash -c 'echo > /dev/tcp/localhost/80'"
      interval: "2s"
      timeout: "1s"
      retries: 10
      start_period: "5s"

  # Environment of the pre-commit linter.
  pre-commit:
    profiles:
      - test
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-pre-commit/upx-pre-commit:latest
    volumes:
      - type: bind
        source: .
        target: /code
      - type: volume
        # pre-commit installs dependencies, having them cached speeds things up
        # a lot.
        source: pre-commit-cache
        target: /cache

volumes:
  # listener only
  listener-data:
  pre-commit-cache:

  # Notifier + OpenLDAP
  ldap-shared-data:
  ldap-shared-run:

...
