---

services:
  listener:
    platform: "linux/amd64"
    image: "gitregistry.knut.univention.de/univention/customers/dataport/upx/container-listener-base/listener-base:latest"
    build:
      context: "."
      args:
        DEBIAN_BASE_IMAGE_TAG: "buster-slim"
    environment:
      # The default configuration matches the state in "container-ldap".
      # See "docker-compose.override.yaml.example" how to tweak this to your needs.
      LDAP_HOST: "${DOCKER_HOST_INTERNAL}"
      LDAP_PORT: "389"
      LDAP_BASE_DN: "dc=univention-organization,dc=intranet"
      # TODO: Set to a reasonable default value, "container-ldap" does not have this yet.
      LDAP_HOST_DN: "cn=ucs-5746,cn=dc,cn=computers,dc=univention-organization,dc=intranet"
      NOTIFIER_SERVER: "${DOCKER_HOST_INTERNAL}"

      DEBUG_LEVEL: "5"
      # Whenever to start encryption. Chose from "never", "request" and "require".
      START_TLS: "never"
      TLS_REQCERT: "never"
      LDAP_BIND_SECRET: "/run/secrets/ldap_secret"
      CA_CERT_FILE: "/run/secrets/ca_cert"
    secrets:
      - "ca_cert"
      - "ldap_secret"
    volumes:
      - "listener-data:/var/lib/univention-directory-listener/:rw"

secrets:
  ca_cert:
    file: "ssl/certs/CAcert.pem"
  ldap_secret:
    file: "secret/ldap.secret"
volumes:
  listener-data:

...
