---

services:
  listener:
    platform: "linux/amd64"
    image: "gitregistry.knut.univention.de/univention/customers/dataport/upx/container-listener-base/listener-base:latest"
    build:
      context: "."
      args:
        DEBIAN_BASE_IMAGE_TAG: "buster-slim"
    environment:
      # The default configuration matches the state in "container-ldap".
      # See "docker-compose.override.yaml.example" how to tweak this to your needs.
      LDAP_HOST: "${DOCKER_HOST_INTERNAL}"
      LDAP_PORT: "389"
      LDAP_BASE_DN: "dc=univention-organization,dc=intranet"
      # TODO: Set to a reasonable default value, "container-ldap" does not have this yet.
      LDAP_HOST_DN: "cn=ucs-5746,cn=dc,cn=computers,dc=univention-organization,dc=intranet"
      NOTIFIER_SERVER: "${DOCKER_HOST_INTERNAL}"

      DEBUG_LEVEL: "5"
      # Whether to start encryption and validate certificates.
      # Chose from "off", "unvalidated" and "secure".
      TLS_MODE: "secure"
      LDAP_PASSWORD: "univention"
      LDAP_PASSWORD_FILE: "/var/secrets/ldap_secret"
      CA_CERT_FILE: "/run/secrets/ca_cert"
    secrets:
      - "ca_cert"
      - "ldap_secret"
    volumes:
      - "listener-data:/var/lib/univention-directory-listener/:rw"

  # Environment of the pre-commit linter.
  pre-commit:
    profiles:
      - test
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-pre-commit/upx-pre-commit:latest
    volumes:
      - type: bind
        source: .
        target: /code
      - type: volume
        # pre-commit installs dependencies, having them cached speeds things up
        # a lot.
        source: pre-commit-cache
        target: /cache


secrets:
  ca_cert:
    file: "ssl/certs/CAcert.pem"
  ldap_secret:
    file: "secret/ldap.secret"

volumes:
  listener-data:
  pre-commit-cache:

...
