# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---

listenerBase:
  environment: "staging"
  caCert: "s3cr3t"
  caCertFile: "/var/secrets/ca_cert"
  debugLevel: "5"
  ldapBaseDn: "dc=univention,dc=intranet"
  ldapPassword: "s3cr3t"
  ldapPasswordFile: "/var/secrets/ldap_secret"
  ldapHost: "ucs-machine"
  ldapHostDn: "cn=ucs-machine,cn=dc,cn=computers,dc=univention,dc=intranet"
  tlsMode: "unvalidated"

...
