---
- name: Fetch secrets from UCS machine
  hosts: ucs_primary

  tasks:
  - name: Fetch LDAP password
    ansible.builtin.fetch:
      src: /etc/ldap.secret
      dest: ../secret/ldap.secret
      flat: true

  - name: Fetch CAcert.pem
    ansible.builtin.fetch:
      src: /etc/univention/ssl/ucsCA/CAcert.pem
      dest: ../ssl/certs/CAcert.pem
      flat: true

  - name: Fetch cert.pem
    ansible.builtin.fetch:
      src: /etc/univention/ssl/{{ ansible_fqdn}}/cert.pem
      dest: ../ssl/certs/cert.pem
      flat: true

  - name: Register LDAP base from UCR
    ansible.builtin.command: ucr get ldap/base
    register: ldap_base

  - name: Configure .env.listener
    ansible.builtin.template:
      src: ./templates/dotenv.listener.j2
      dest: ../.env.listener
    delegate_to: localhost

  - name: Configure docker-compose.override.yaml
    ansible.builtin.template:
      src: ./templates/docker-compose.override.yaml.j2
      dest: ../docker-compose.override.yaml
    delegate_to: localhost
