# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2025 Univention GmbH


{{- if .Values.serviceAccount.create -}}
---

apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: '{{ include "common.names.fullname" . }}'
  labels:
    {{- include "listener-base.labels" . | nindent 4 }}
  {{- with (merge .Values.additionalAnnotations .Values.serviceAccount.annotations) }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl ($value | toString) $ | quote }}
    {{- end }}
  {{- end }}

...
{{- end }}
